version: "3.9"

services:
  scraper:
    build: .
    container_name: selenium_scraper
    volumes:
      - .:/app
      - ../data/raw:/app/data/raw
      - ../logger:/app/logger 
    env_file:
      - .env        
    environment:
      - DISPLAY=:99
    shm_size: '2gb'   
